### ISSUE TITLE
Typo server code LedRing.cpp?

### ISSUE THREAD

**Issue by Riposte63** [Yohannfra/Touche#17]
Hi,
I've been trying to familiarise myself with the project code while I await the arrival of parts to make it.
In the process I think I may have spotted a typo in the show_hits function. 
Line 113: 
else if (action_player2 == ActionManager::VALID_HIT) 
I think should be
else if (action_player2 == ActionManager::INVALID_HIT)  ??

PS: I'm really enjoying learning about this project - you are doing great work!!

**Comment by Yohannfra** [comment]
Thanks you for spotting this one !  😃
