### ISSUE TITLE
Only one client working -> confused by the led color perhaps

### ISSUE THREAD

**Issue by Ajeistir** [Yohannfra/Touche#18]
Hello Yohann and first of all, congrats for this great project!

I follow your instructions scrupulously but my client #1 is not working. The #2 seems to be ok (the touch is shown on the server) but before redoing the first one from scratch, I've to be sure that #2 is really runnning fine. So my concern is the color of the client's led when "touché" (sorry, I'm french too ;) ) : I've got a green light when I expect a red one no? Also, speaking about the client's led, you said : 
" Turn on of the client, if the led is :
Red -> Epee mode"
It"s a (very) brief light right?

**Comment by timeglitch** [comment]
Come on, are you going to close this without telling us what the problem was?
